x-debian-version: &debian-version 13
x-debian-image: &debian-image "lcs-native:debian-13"
x-puid: &puid 1000
x-pgid: &pgid 1000

services:
  build-archlinux:
    image: "lcs-native:archlinux"
    build:
      context: "."
      dockerfile: "archlinux.Dockerfile"
      args:
        PUID: *puid
        PGID: *pgid
    volumes:
      - "../:/home/build/lcs-recomp/"
      - "./ccache-archlinux/:/home/build/.ccache/"
  build-debian:
    image: *debian-image
    build:
      context: "."
      dockerfile: "debian.Dockerfile"
      args:
        DEBIAN_VERSION: *debian-version
        PUID: *puid
        PGID: *pgid
    volumes:
      - "../:/home/build/lcs-recomp/"
      - "./ccache-debian/:/home/build/.ccache/"
  build-windows:
    image: "lcs-native:windows-msvc"
    build:
      context: "."
      dockerfile: "windows-msvc.Dockerfile"
    user: "${HOST_UID:-1000}:${HOST_GID:-1000}"
    environment:
      HOME: /tmp
    working_dir: /src
    volumes:
      - "../:/src/"
      - "./ccache-windows/:/ccache/"
    command: ["bash", "/src/docker/compile_windows.sh"]
